@startuml
title Book Roadmap
' This diagram represents the roadmap of the book "Spring Boot and Angular - 2nd Edition"
' It is divided into four main parts, each focusing on different aspects of building a full-stack application.

start
card **Part 1: Foundations**{
  :1. Spring Boot and Angular: The Big Picture and Kickstart the Environment;
}

' floating note: current chapter

card **Part 2: Backend Deep Dive** {
  :2. Getting started with microservices using Spring Boot
3. Setting up database and repositories using Spring Data JPA
4. Building application services and APls with Spring
5. Developing API Gateway using Spring Cloud
6. Documenting APls with OpenAPl and logging the events.
7. Securing microservice using Spring Boot Security and JWT
8. End-to-end microservices components testing
9. Reactive programming using Spring;
}
' floating note: Note on Partition

card **Part 3: Frontend Evolution** {
  :10. Setting up Angular project and architecture
11. Building Forms with Reactive Patters
12. Managing State with Signals and Stores
13. Performing CRUD Operations with State Management
14. Adding authentication in Angular
15. Writing tests in Angular
16. Server-Side Rendering with Angular (SSR)
17. Handling Real-Time Data with Angular;
}
' floating note: Note on Package 

card **Part 4: Production Readiness**{
  :18. Building and Packaging the Spring Boot Backend
19. Building and Deploying the Angular Frontend
20. Connecting Frontend and Backend in Production;
}
end
@enduml
